apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rwal
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rwal
    app.kubernetes.io/part-of: byoc-app-wjqe
  name: rwal
spec:
  rules:
  - host: rwal-byoc-hjad-tenant.apps.10225eb6e484bd08b4ab.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: rwal
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
