apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rwal
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rwal
    app.kubernetes.io/part-of: byoc-app-wjqe
  name: rwal
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: rwal
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: rwal
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-hjad-tenant/byoc-app-wjqe/rwal@sha256:df5b78cb557dc60dfb0f3d88fd118d32a7e9e82bcd6e0e4dbd974d741eaae170
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
